#define PIC_NONE		0
#define PIC_WARRIOR		1
#define PIC_PALADIN		2
#define PIC_ROGUE		3
#define PIC_BARD		4
#define PIC_HUNTER		5
#define PIC_MONK		6
#define PIC_CONJURER		7
#define PIC_MAGICIAN		8
#define PIC_SORCEROR		9
#define PIC_WIZARD		10
#define PIC_ARCHMAGE		11
#define PIC_TREASURE		12
#define PIC_GAMEOVER		13
#define PIC_MAGICMOUTH		14
#define PIC_BANKINT		15
#define PIC_IRONGATE		16
#define PIC_TEMPLEEXT		17
#define PIC_BAREXT		18
#define PIC_GARTHEXT		19
#define PIC_GUILDINT		20
#define PIC_CREDITS		21
#define PIC_GUILDEXT		22
#define PIC_EMPTYHUT		23
#define PIC_CHEST		24
#define PIC_BARINT		25
#define PIC_GARTHINT		26
#define PIC_TEMPLEINT		27
#define PIC_REVINT		28
#define PIC_ROSCOEINT		29
#define PIC_EMPTYBLDG		30
#define PIC_DRAGON		31
#define PIC_MAGE		32
#define PIC_ZOMBIE		33
#define PIC_DAEMON		34
#define PIC_GIANT		35
#define PIC_SKELETON		36
#define PIC_ARCHER		37
#define PIC_GUARDIAN		38
#define PIC_VAMPIRE		39
#define PIC_MEDUSA		40
#define PIC_KOBOLD		41
#define PIC_NINJA		42
#define PIC_ZENDAR		43
#define PIC_TOXICGIANT		44
#define PIC_GOLEM		45
#define PIC_LIZARD		46
#define PIC_VICTORY		47
#define PIC_FORGESEGMENT		48
#define PIC_ROCKGIANT		49
#define PIC_PRIEST		50
#define PIC_FIEND		51
#define PIC_OGRE		52
#define PIC_CLOUDGIANT		53
#define PIC_DREN		54
#define PIC_BUGGER		55
#define PIC_GUARD		56
#define PIC_SAGE		57
#define PIC_DEATHDEALER		58
#define PIC_DOG		59
#define PIC_TITAN		60
