#include <b2lib.h>
#include <dun.h>

b2levData_t b2dungeons[] = {
	{ "domain",	4, { 0,  1,  2,  3, -1 }},
	{ "tombs",	3, { 4,  5,  6, -1, -1 }},
	{ "castle",	1, { 7, -1, -1, -1, -1 }},
	{ "tower", 	5, { 8,  9, 10, 11, 12 }},
	{ "maze",	3, {13, 14, 15, -1, -1 }},
	{ "fort",	4, {16, 17, 18, 19, -1 }},
	{ "crypt",	2, {20, 21, -1, -1, -1 }},
	{ "stone",	3, {22, 23, 24, -1, -1 }}
};

uint8_t	*levelTypes[] = {
	"wild",
	"city"
};

uint8_t	*directions[] = {
	"north",
	"west",
	"south",
	"east"
};

uint8_t	dunExitDirection[] = {
	0, 3, 2, 3, 0, 2, 2, 0, 1
};

uint8_t	*dunExitLocations[] = {
	"wild",
	"Tangramayne",
	"Ephesus",
	"Philippi",
	"Colosse",
	"Corinth",
	"Thessalonica"
};

uint8_t *b2dun_specialCode[] = {
	"--tombs_Mouth1",
	"--_magic_mouth_1",
	"--_statue_1",
	"--masterKeyCheck",
	"--_magic_mouth_2",
	"--deadKing",
	"--_oldman_fireball",
	"--snare_1",
	"--_battle_1",
	"--toxicGiant",
	"--fountain",
	"--partyHasSeg1",
	"--fanskarBodyguard",
	"--_magic_mouth_3",
	"--fanskar",
	"--partyHasSeg2",
	"--fieryDeath",
	"--oldmanBlackHint",
	"--oldmanWhiteHint",
	"--_magic_mouth_4",
	"--_magic_mouth_5",
	"--sevenStatues",
	"--_magic_mouth_6",
	"--_magic_mouth_7",
	"--_magic_mouth_8",
	"--dargoth",
	"--partyHasSeg3",
	"--genericMagicMouth",
	"--_statue_2",
	"--addDagger",
	"--mageHint",
	"--magicMouth10",
	"--elevator",
	"--partyHasSwordOfZar",
	"--graphnarMercs",
	"--graphnarSchool",
	"--enterSnare4",
	"--addVialToParty",
	"--keepTheFaith",
	"--_magic_mouth_10",
	"--partyHasSeg4",
	"--_magic_mouth_11",
	"--_magic_mouth_12",
	"--_magic_mouth_13",
	"--_magic_mouth_14",
	"--tripwire",
	"--OsconsMirrorRoom",
	"--_magic_mouth_15",
	"--dervak",
	"--tripwire_2",
	"--osconsFunhouse",
	"--_magic_mouth_17",
	"--Oscon",
	"--enterSnare5",
	"--rockStatue",
	"--paperStatue",
	"--scissorStatue",
	"--RPSCheck",
	"--partyHasSeg5",
	"--fieryDeath",
	"--doNothing",
	"--doNothing",
	"--doNothing",
	"--doNothing",
	"--sphinxHint",
	"--sphinx",
	"--enterSnare6",
	"--_snare_6_sq1",
	"--_snare_6_sq2",
	"--_snare_6_sq3",
	"--_snare_6_sq4",
	"--blueMage",
	"--greyMage",
	"--_remove_spinner",
	"--_magic_mouth_16",
	"--_oldman_1",
	"--_battle_2",
	"--_magic_mouth_18",
	"--_magic_mouth_19",
	"--twoDoors",
	"--chasm",
	"--princess",
	"--darkLord",
	"--doNothing",
	"--doNothing",
	"--oldman_near",
	"--paleOldMan",
	"--smallYellowDragon",
	"--blueLizard",
	"--knightStatue",
	"--goUpLevel",
	"--enterSnare7",
	"--zenMaster",
	"--stormFist",
	"--enterSnare6_1",
	"--ancientScribe",
	"--arkast",
	"--getZenMaster",
	"--getSegment7"
};
