#define	SP_MAFL	0
#define	SP_ARFI	1
#define	SP_TRZP	2
#define	SP_FRFO	3
#define	SP_MACO	4
#define	SP_WOHL	5
#define	SP_LERE	6
#define	SP_LEVI	7
#define	SP_WAST	8
#define	SP_INWO	9
#define	SP_FLRE	10
#define	SP_GRRE	11
#define	SP_SHSP	12
#define	SP_INOG	13
#define	SP_MALE	14
#define	SP_FLAN	15
#define	SP_APAR	16
#define	SP_FAFO	17
#define	SP_INSL	18
#define	SP_VOPL	19
#define	SP_QUFI	20
#define	SP_SCSI	21
#define	SP_HOWA	22
#define	SP_MAGA	23
#define	SP_AREN	24
#define	SP_MYSH	25
#define	SP_OGST	26
#define	SP_STFL	27
#define	SP_SPTO	28
#define	SP_DRBR	29
#define	SP_ANMA	30
#define	SP_STTO	31
#define	SP_PHDO	32
#define	SP_YMCA	33
#define	SP_REST	34
#define	SP_DEST	35
#define	SP_WZWA	36
#define	SP_SASP	37
#define	SP_MIJA	38
#define	SP_PHBL	39
#define	SP_LOTR	40
#define	SP_DISB	41
#define	SP_WIWA	42
#define	SP_FEAR	43
#define	SP_WIOG	44
#define	SP_INVI	45
#define	SP_SESI	46
#define	SP_CAEY	47
#define	SP_WIDR	48
#define	SP_DIIL	49
#define	SP_MIBL	50
#define	SP_WIGI	51
#define	SP_SOSI	52
#define	SP_WIMA	53
#define	SP_WIHE	54
#define	SP_MAGM	55
#define	SP_ZZGO	56
#define	SP_SUEL	57
#define	SP_FOFO	58
#define	SP_GATE	59
#define	SP_DEBA	60
#define	SP_FLCO	61
#define	SP_DISP	62
#define	SP_PRSU	63
#define	SP_ANDE	64
#define	SP_SPBI	65
#define	SP_SOWH	66
#define	SP_GRSU	67
#define	SP_BEDE	68
#define	SP_WIZW	69
#define	SP_HERB	70
#define	SP_HAFO	71
#define	SP_MEME	72
#define	SP_BASP	73
#define	SP_CAMR	74
#define	SP_NILA	75
#define	SP_HEAL	76
#define	SP_BRKR	77
#define	SP_MAMA	78
