#include <b2lib.h>
#include <fileio.h>

static uint8_t *picMac[] = {
/*  0*/"PIC_WARRIOR", "PIC_PALADIN", "PIC_ROGUE", "PIC_BARD",
/*  4*/"PIC_HUNTER", "PIC_MONK", "PIC_CONJURER", "PIC_MAGICIAN",
/*  8*/"PIC_SORCERER", "PIC_WIZARD", "PIC_ARCHMAGE", "PIC_TREASURE",
/* 12*/"PIC_GAMEOVER", "PIC_MAGICMOUTH", "PIC_BANKINT", "PIC_IRONGATE",
/* 16*/"PIC_TEMPLEEXT", "PIC_BAREXT", "PIC_GARTHEXT", "PIC_GUILDINT",
/* 20*/"PIC_CREDITS", "PIC_GUILDEXT", "PIC_EMPTYHUT", "PIC_CHEST",
/* 24*/"PIC_BARINT", "PIC_NONE1", "PIC_GARTHINT", "PIC_TEMPLEINT",
/* 28*/"PIC_REVINT", "PIC_ROSCOEINT", "PIC_NONE2", "PIC_EMPTYBLDG",
/* 32*/"PIC_DRAGON", "PIC_MAGE", "PIC_ZOMBIE", "PIC_DAEMON",
/* 36*/"PIC_GIANT", "PIC_SKELETON", "PIC_ARCHER", "PIC_GUARDIAN",
/* 40*/"PIC_VAMPIRE", "PIC_MEDUSA", "PIC_KOBOLD", "PIC_NINJA",
/* 44*/"PIC_ROSCOEEXT", "PIC_ZENDAR", "PIC_TOXICGIANT", "PIC_GOLEM",
/* 48*/"PIC_LIZARD", "PIC_VICTORY", "PIC_FORGESEGMENT", "PIC_REVEXT",
/* 52*/"PIC_GOLEM", "PIC_PRIEST", "PIC_FIEND", "PIC_OGRE",
/* 56*/"PIC_CLOUDGIANT", "PIC_DREN", "PIC_BUGGER", "PIC_GUARD",
/* 60*/"PIC_SAGE", "PIC_DEATHDEALER", "PIC_DOG", "PIC_TITAN",
};

btstring_t *getPicMacro(uint8_t pi)
{
  return bts_strcpy(picMac[pi]);
}
